/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AutoDao;
import View.Model.TableAuto;
import javax.swing.JOptionPane;
import lista.Controller.Lista;

/**
 *
 * @author Home
 */
public class Frm_Auto extends javax.swing.JDialog {
    private TableAuto modelo = new TableAuto();
    private AutoDao autoDao = new AutoDao();

    /**
     * Creates new form Frm_Auto
     */
    public Frm_Auto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        limpiar();
    }
    private void cargarTable(){
        modelo.setLista(autoDao.listar());
        tableauto.setModel(modelo);
        tableauto.updateUI();
    }
    private void limpiar(){
        autoDao.setAuto(null);
        cargarTable();
        txtmodelo.setText("");
        txtcolor.setText("");
        txtplaca.setText("");
    }
    private boolean validar(){
        return (txtmodelo.getText().trim().length() > 0 && txtcolor.getText().trim().length() > 0
                && txtplaca.getText().trim().length() > 0);
    }
    private void guardar(){
        if(validar()){
            autoDao.getAuto().setModelo(txtmodelo.getText().trim());
            autoDao.getAuto().setColor(txtcolor.getText().trim());
            autoDao.getAuto().setPlaca(txtplaca.getText().trim());
            if (autoDao.guardar()) {
                JOptionPane.showMessageDialog(null, "Guardado correctamente", "OK", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            }else{
                JOptionPane.showMessageDialog(null, "Error al guardar", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Llene todos los compos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void ordenar(){
        int select = cbxordenacion.getSelectedIndex();
        String atributo = "modelo";
        if (select == 0) {
            cargarTable();
        }else if(select == 1){
            Lista aux = autoDao.listar();
            aux.Ordenar_Shell(atributo, aux);
            modelo.setLista(aux);
            tableauto.setModel(modelo);
        }else{
            Lista aux = autoDao.listar();
            aux.ordenarQuicksort3(aux, 0, aux.tamanio()-1);
            modelo.setLista(aux);
            tableauto.setModel(modelo);
        }
        tableauto.updateUI();
    }
    private void buscar(){
        int select = cbxbusqueda.getSelectedIndex();
        Lista aux = new Lista();
        switch(select){
            case 0: aux = autoDao.listar();break;
            case 1: aux = autoDao.buscarPorModelo(txtbusqueda.getText(), modelo.getLista());break;
            default: aux = modelo.getLista();
        }
        modelo.setLista(aux);
        tableauto.setModel(modelo);
        tableauto.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtplaca = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        txtcolor = new javax.swing.JTextField();
        BTNGUARDAR = new javax.swing.JButton();
        BTNSALIR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableauto = new javax.swing.JTable();
        cbxordenacion = new javax.swing.JComboBox<>();
        txtbusqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxbusqueda = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Placa:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(320, 50, 41, 16);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Modelo:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 50, 43, 16);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Color:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 100, 41, 16);
        jPanel2.add(txtplaca);
        txtplaca.setBounds(380, 40, 120, 30);
        jPanel2.add(txtmodelo);
        txtmodelo.setBounds(70, 40, 120, 30);
        jPanel2.add(txtcolor);
        txtcolor.setBounds(70, 90, 120, 30);

        BTNGUARDAR.setText("GUARDAR");
        BTNGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGUARDARActionPerformed(evt);
            }
        });
        jPanel2.add(BTNGUARDAR);
        BTNGUARDAR.setBounds(310, 100, 90, 24);

        BTNSALIR.setText("SALIR");
        jPanel2.add(BTNSALIR);
        BTNSALIR.setBounds(430, 100, 70, 24);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE AUTOS");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(170, 10, 190, 16);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 530, 150);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(null);

        tableauto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableauto);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(200, 10, 320, 150);

        cbxordenacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Shell", "QuickSort" }));
        cbxordenacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxordenacionItemStateChanged(evt);
            }
        });
        jPanel4.add(cbxordenacion);
        cbxordenacion.setBounds(50, 130, 100, 26);
        jPanel4.add(txtbusqueda);
        txtbusqueda.setBounds(10, 70, 100, 30);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(120, 70, 70, 24);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Busqueda Binara");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 10, 150, 20);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Metodos Ordenacion");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(30, 100, 150, 20);

        cbxbusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Modelo" }));
        jPanel4.add(cbxbusqueda);
        cbxbusqueda.setBounds(10, 30, 110, 26);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 170, 530, 170);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 550, 350);

        setSize(new java.awt.Dimension(584, 410));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGUARDARActionPerformed
        if (autoDao.getAuto().getId() != null) {
            //modificar
        }else{
        guardar();
        }
    }//GEN-LAST:event_BTNGUARDARActionPerformed

    private void cbxordenacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxordenacionItemStateChanged
        ordenar();
    }//GEN-LAST:event_cbxordenacionItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        buscar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Auto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Auto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Auto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Auto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_Auto dialog = new Frm_Auto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNGUARDAR;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JComboBox<String> cbxbusqueda;
    private javax.swing.JComboBox<String> cbxordenacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableauto;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtplaca;
    // End of variables declaration//GEN-END:variables
}
